[package]
name = "port-scann"
version = "0.1.0"
authors = ["chansuke <chansuke@georepublic.de>"]
edition = "2018"

[dependencies]
pnet = "0.22.0"
rayon = "1.0"
log = "0.4"
env_logger = "0.6.1"
failure = "0.1.5"
